# Generated by Django 5.1.3 on 2024-11-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productsize_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
